version: '3'

services: 
    jupyterlab:
        image: datafuel/jupyterlab
        environment:
            - TOKEN=$TOKEN
        working_dir: /home/notebooks
        command: "jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=$TOKEN"
        volumes: 
            - ./notebooks:/home/notebooks
        ports:
            - 8888:8888

networks: 
    default: 
        external: 
            name: datafuel-local-network
     