version: '3'

services: 
    jupyterlab:
        container_name: jupyterlab
        image: datafuel/jupyterlab
        environment:
            - TOKEN=$TOKEN
        command: "jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=$TOKEN"
        volumes: 
            - ./notebooks:/home/notebooks
        ports:
            - 8888:8888
    selenium:
        container_name: selenium
        image: selenium/standalone-chrome
        ports:
            - 4444:4444